server:
  error:
    include-message: always
    include-binding-errors: on-param

springdoc:
  swagger-ui:
    enabled: true

spring:
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ""
            client-secret: ""

app:
  cors:
    allow_all_origins: true
  cookies:
    secure: false
